safe:        true
auto:        true
server:      false
server_port: 4000
baseurl:     /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: [no_intra_emphasis]

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

nav_items:
- url: /pages/concerns.html
  text: Concerns
  nav_id: concerns
- url: /pages/configuration.html
  text: Configuration
  nav_id: configuration
- url: /pages/documentation.html
  text: Documentation
  nav_id: documentation
- url: /pages/how_to_change_objects.html
  text: How to change objects
  nav_id: how_to_change_objects
- url: /pages/naming_and_organizing_your_user_facing_code.html
  text: Naming and organizing your user facing code
  nav_id: naming_and_organizing_your_user_facing_code
- url: /pages/outcome.html
  text: Outcome
  nav_id: outcome
- url: /pages/permissions_and_user_roles.html
  text: Permissions and user roles
  nav_id: permissions_and_user_roles
- url: /pages/ruby_coding_style_guide.html
  text: Ruby coding style guide
  nav_id: ruby_coding_style_guide
